/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dean_testndk_JNIHelper */

#ifndef _Included_com_dean_testndk_JNIHelper
#define _Included_com_dean_testndk_JNIHelper

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dean_testndk_JNIHelper
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dean_testndk_JNIHelper_getStringFromNative
  (JNIEnv *, jclass);


JNIEXPORT void JNICALL
        Java_com_dean_testndk_MainActivity_doCalcPlus(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
